### ISSUE TITLE
Can't deconstruct Furniture

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#639]
Can't seem to decontruct funiture at the moment.

**Comment by dustinwloring1988** [comment]
I will fix in a PR I have pending

**Comment by dustinwloring1988** [comment]
Fixed

**Comment by Mizipzor** [comment]
Pull request was never accepted, I assume this is still an issue.

**Comment by GamerInspired** [comment]
I can't currently test this as I'm away from my main machine. Could someone else check this for me.

**Comment by Mizipzor** [comment]
No rush. :)

**Comment by abackwood** [comment]
Can confirm. The furniture deconstruct button doesn't seem to be doing anything

**Comment by GamerInspired** [comment]
Just found out during my once a day (minimum) test session. That you can deconstuct things but only using the right click and selecting deconstruct method.

**Comment by sboigelot** [comment]
Deconstruction works again (from CM & from the build menu button).
We can close this issue
